import React, { useState } from 'react';
import './App.css';
import ChatBox from './components/ChatBox';
import PerspectiveSelector from './components/PerspectiveSelector';

function App() {
  const [selectedPerspective, setSelectedPerspective] = useState(null);
  const [chatHistory, setChatHistory] = useState([]);

  const handleSendMessage = (message) => {
    // Add user message to chat
    setChatHistory([...chatHistory, { sender: 'user', text: message }]);
    
    // Simulate AI response (in a real app, this would call an API)
    setTimeout(() => {
      const response = `Response from ${selectedPerspective} perspective: This is a simulated response. In a complete implementation, this would be generated by an AI model representing the ${selectedPerspective} perspective.`;
      setChatHistory([...chatHistory, { sender: 'user', text: message }, { sender: 'ai', text: response }]);
    }, 1000);
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>Political Perspectives Chat</h1>
        <p>Chat with AIs representing different political viewpoints</p>
      </header>
      <main>
        <PerspectiveSelector onSelect={setSelectedPerspective} selected={selectedPerspective} />
        <ChatBox 
          chatHistory={chatHistory} 
          onSendMessage={handleSendMessage} 
          selectedPerspective={selectedPerspective}
        />
      </main>
    </div>
  );
}

export default App; 